# Generated by Django 5.0.6 on 2025-10-31 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_logauditoria_notificacao'),
        ('agenda', '0002_initial'),
        ('atendimento', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo da Visita')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_desejada', models.DateField(verbose_name='Data Desejada')),
                ('horario_preferencia', models.CharField(help_text='Ex: Manhã, Tarde, 14h', max_length=50, verbose_name='Horário de Preferência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Confirmação'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('protocolo', models.CharField(max_length=20, unique=True, verbose_name='Protocolo')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('resposta_cidadao', models.TextField(blank=True, verbose_name='Resposta ao Cidadão')),
                ('data_confirmada', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Confirmada')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('evento_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento_origem', to='agenda.evento', verbose_name='Evento Criado')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_visitas', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Agendamento de Visita',
                'verbose_name_plural': 'Agendamentos de Visitas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('resumo', models.TextField(blank=True, help_text='Resumo que aparece na listagem', max_length=500, verbose_name='Resumo')),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Notícia'), ('RELATORIO', 'Relatório'), ('COMUNICADO', 'Comunicado'), ('PRESTACAO_CONTAS', 'Prestação de Contas'), ('EVENTO', 'Evento/Atividade')], default='NOTICIA', max_length=20, verbose_name='Tipo')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=200, verbose_name='Tags')),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='portal/publicacoes/%Y/%m/', verbose_name='Imagem de Destaque')),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='portal/anexos/%Y/%m/', verbose_name='Arquivo Anexo')),
                ('link_externo', models.URLField(blank=True, verbose_name='Link Externo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=30, verbose_name='Status')),
                ('publico', models.BooleanField(default=False, verbose_name='Visível ao Público')),
                ('destaque', models.BooleanField(default=False, verbose_name='Publicação em Destaque')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='accounts.assunto', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_publicacao', '-criado_em'],
                'indexes': [models.Index(fields=['gabinete', 'publico', 'status'], name='portal_publ_gabinet_9bc4c7_idx'), models.Index(fields=['data_publicacao'], name='portal_publ_data_pu_90382c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, help_text='Opcional, mas ajuda a identificar', max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail para Contato')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('tipo_solicitacao', models.CharField(max_length=100, verbose_name='Tipo de Solicitação')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('protocolo_publico', models.CharField(help_text='Protocolo para consulta pública', max_length=20, unique=True, verbose_name='Protocolo Público')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESPONDIDA', 'Respondida'), ('ATENDIMENTO_CRIADO', 'Atendimento Criado'), ('ARQUIVADA', 'Arquivada')], default='PENDENTE', max_length=30, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta/Parecer')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('consentimento_lgpd', models.BooleanField(default=False, help_text='Cidadão autorizou tratamento de dados', verbose_name='Consentimento LGPD')),
                ('consentimento_texto', models.TextField(blank=True, verbose_name='Texto do Consentimento')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='portal/solicitacoes/%Y/%m/', verbose_name='Anexo')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendimento_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='atendimento.atendimento', verbose_name='Atendimento Gerado')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_publicas', to='accounts.gabinete', verbose_name='Gabinete')),
                ('pessoa_criada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_publicas', to='crm.pessoa', verbose_name='Pessoa Criada no CRM')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Solicitação Pública',
                'verbose_name_plural': 'Solicitações Públicas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['gabinete', 'status'], name='portal_soli_gabinet_56391f_idx'), models.Index(fields=['protocolo_publico'], name='portal_soli_protoco_436217_idx'), models.Index(fields=['cpf'], name='portal_soli_cpf_504d03_idx'), models.Index(fields=['email'], name='portal_soli_email_520c3b_idx')],
            },
        ),
    ]
