# Generated by Django 5.0.6 on 2025-10-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Órgão',
                'verbose_name_plural': 'Tipos de Órgão',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='destinatario',
            options={'ordering': ['nome'], 'verbose_name': 'Destinatário Padrão', 'verbose_name_plural': 'Destinatários Padrões'},
        ),
        migrations.AddField(
            model_name='destinatario',
            name='cargo',
            field=models.CharField(default='Não informado', help_text='Ex: Secretário, Diretor, Prefeito', max_length=200, verbose_name='Cargo/Função'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='municipio',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='nivel_administrativo',
            field=models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('ESTADUAL', 'Estadual'), ('FEDERAL', 'Federal'), ('OUTRO', 'Outro')], default='MUNICIPAL', max_length=20, verbose_name='Nível Administrativo'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Ex: Solicitar protocolo ao enviar ofício', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='uf',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF (Estado)'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='email',
            field=models.EmailField(default='sem-email@exemplo.com', max_length=254, verbose_name='E-mail Institucional'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='orgao',
            field=models.CharField(default='Não informado', help_text='Ex: Secretaria Municipal de Obras', max_length=200, verbose_name='Órgão/Instituição'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='tipo_orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatarios', to='documentos.tipoorgao', verbose_name='Tipo de Órgão'),
        ),
    ]
