# Generated by Django 5.0.6 on 2025-10-14 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('documentos', '0002_tipoorgao_alter_destinatario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='pessoa_interessada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_interessada', to='crm.pessoa', verbose_name='Pessoa Interessada'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Ofício'),
        ),
        migrations.AddField(
            model_name='memorando',
            name='pessoa_interessada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_interessada', to='crm.pessoa', verbose_name='Pessoa Interessada'),
        ),
        migrations.AddField(
            model_name='memorando',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Ofício'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='pessoa_interessada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_interessada', to='crm.pessoa', verbose_name='Pessoa Interessada'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Ofício'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='pessoa_interessada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_interessada', to='crm.pessoa', verbose_name='Pessoa Interessada'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Ofício'),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_VALIDACAO', 'Em Validação'), ('CONCLUIDO', 'Concluído'), ('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('ENVIADO', 'Enviado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='memorando',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_VALIDACAO', 'Em Validação'), ('CONCLUIDO', 'Concluído'), ('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('ENVIADO', 'Enviado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_VALIDACAO', 'Em Validação'), ('CONCLUIDO', 'Concluído'), ('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('ENVIADO', 'Enviado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_VALIDACAO', 'Em Validação'), ('CONCLUIDO', 'Concluído'), ('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('ENVIADO', 'Enviado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
