# Generated by Django 5.0.6 on 2025-10-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documentos', '0003_indicacao_pessoa_interessada_indicacao_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacao',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='memorando',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número do Documento'),
        ),
        migrations.AlterUniqueTogether(
            name='indicacao',
            unique_together={('gabinete', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='memorando',
            unique_together={('gabinete', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together={('gabinete', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='requerimento',
            unique_together={('gabinete', 'numero')},
        ),
    ]
