# Generated by Django 5.0.6 on 2025-10-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_justificativapadrao'),
        ('documentos', '0004_alter_indicacao_numero_alter_memorando_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='justificativa_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_utilizando', to='accounts.justificativapadrao', verbose_name='Justificativa Padrão'),
        ),
    ]
