# Generated by Django 5.0.6 on 2025-10-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_solicitacaopadrao'),
        ('documentos', '0005_oficio_justificativa_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='solicitacao_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_utilizando', to='accounts.solicitacaopadrao', verbose_name='Solicitação Padrão'),
        ),
    ]
