# Generated by Django 5.0.6 on 2025-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('SESSAO_PLENARIA', 'Sessão Plenária'), ('SESSAO_EXTRAORDINARIA', 'Sessão Extraordinária'), ('COMISSAO', 'Reunião de Comissão'), ('AUDIENCIA_PUBLICA', 'Audiência Pública'), ('AUDIENCIA_PRIVADA', 'Audiência Privada'), ('ATENDIMENTO', 'Atendimento'), ('REUNIAO_EXECUTIVO', 'Reunião com Executivo'), ('REUNIAO_COMUNIDADE', 'Reunião com Comunidade'), ('REUNIAO_ENTIDADE', 'Reunião com Entidade'), ('REUNIAO_TRABALHO', 'Reunião de Trabalho'), ('EVENTO_PUBLICO', 'Evento Público'), ('INAUGURACAO', 'Inauguração'), ('SOLENIDADE', 'Solenidade'), ('HOMENAGEM', 'Homenagem'), ('VISITA_TECNICA', 'Visita Técnica'), ('FISCALIZACAO', 'Fiscalização'), ('VISTORIA', 'Vistoria'), ('ENTREVISTA', 'Entrevista'), ('COLETIVA', 'Coletiva de Imprensa'), ('GRAVACAO', 'Gravação'), ('VIAGEM', 'Viagem'), ('CAPACITACAO', 'Capacitação/Curso'), ('OUTRO', 'Outro')], default='REUNIAO_TRABALHO', max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ANDAMENTO', 'Em Andamento'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'Adiado')], default='AGENDADO', max_length=20, verbose_name='Status')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=2, verbose_name='Prioridade')),
                ('inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('endereco_completo', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('link', models.URLField(blank=True, verbose_name='Link (reunião online)')),
                ('numero_participantes_esperado', models.IntegerField(blank=True, null=True, verbose_name='Número Esperado de Participantes')),
                ('lembrete_minutos', models.PositiveIntegerField(default=60, help_text='Enviar lembrete X minutos antes', verbose_name='Lembrete (minutos antes)')),
                ('enviar_convite', models.BooleanField(default=False, verbose_name='Enviar Convite por E-mail')),
                ('is_publico', models.BooleanField(default=False, verbose_name='Evento Público')),
                ('is_recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('recorrencia_tipo', models.CharField(blank=True, choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], max_length=20, verbose_name='Tipo de Recorrência')),
                ('ata', models.TextField(blank=True, verbose_name='Ata/Resumo')),
                ('decisoes', models.TextField(blank=True, verbose_name='Decisões Tomadas')),
                ('proximos_passos', models.TextField(blank=True, verbose_name='Próximos Passos')),
                ('arquivos_anexos', models.JSONField(blank=True, default=list, verbose_name='Arquivos Anexos')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('requisitos_especiais', models.TextField(blank=True, verbose_name='Requisitos Especiais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['inicio'],
            },
        ),
    ]
