# Generated by Django 5.0.6 on 2025-10-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agenda', '0001_initial'),
        ('atendimento', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atendimento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gerados', to='atendimento.atendimento', verbose_name='Atendimento de Origem'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='accounts.assunto', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='evento',
            name='gabinete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='accounts.gabinete'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes_equipe',
            field=models.ManyToManyField(blank=True, related_name='eventos_participando', to=settings.AUTH_USER_MODEL, verbose_name='Participantes (Equipe)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes_pessoas',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='crm.pessoa', verbose_name='Participantes (Pessoas)'),
        ),
    ]
