# Generated by Django 5.0.6 on 2025-10-12 19:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Gabinete Vereador João Silva', max_length=200, verbose_name='Nome do Gabinete')),
                ('parlamentar_nome', models.CharField(max_length=200, verbose_name='Nome do Parlamentar/Titular')),
                ('cargo', models.CharField(choices=[('VEREADOR', 'Vereador(a)'), ('PREFEITO', 'Prefeito(a)'), ('VICE_PREFEITO', 'Vice-Prefeito(a)'), ('DEPUTADO_ESTADUAL', 'Deputado(a) Estadual'), ('DEPUTADO_FEDERAL', 'Deputado(a) Federal'), ('SENADOR', 'Senador(a)'), ('GOVERNADOR', 'Governador(a)'), ('SECRETARIO', 'Secretário(a)')], default='VEREADOR', max_length=30, verbose_name='Cargo')),
                ('esfera', models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('ESTADUAL', 'Estadual'), ('FEDERAL', 'Federal')], default='MUNICIPAL', max_length=20, verbose_name='Esfera')),
                ('legislatura_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Legislatura')),
                ('legislatura_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Legislatura')),
                ('numero_legislatura', models.CharField(blank=True, help_text='Ex: 19ª Legislatura', max_length=50, verbose_name='Número/Nome da Legislatura')),
                ('partido_sigla', models.CharField(blank=True, max_length=10, verbose_name='Sigla do Partido')),
                ('partido_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Partido')),
                ('partido_logo', models.ImageField(blank=True, null=True, upload_to='gabinete/logos/partido/', verbose_name='Logo do Partido')),
                ('municipio', models.CharField(default='', max_length=100, verbose_name='Município')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('regiao', models.CharField(blank=True, help_text='Ex: Zona Norte, Vale do Paraíba', max_length=50, verbose_name='Região')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Oficial')),
                ('email_secundario', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Secundário')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, verbose_name='Telefone Secundário')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('site', models.URLField(blank=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gabinete/logos/', verbose_name='Logo do Gabinete')),
                ('brasao_municipio', models.ImageField(blank=True, null=True, upload_to='gabinete/brasao/', verbose_name='Brasão do Município/Estado')),
                ('cor_primaria', models.CharField(default='#0D2A8B', help_text='Ex: #0D2A8B', max_length=7, verbose_name='Cor Primária (HEX)')),
                ('cor_secundaria', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor Secundária (HEX)')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Slogan/Lema')),
                ('missao', models.TextField(blank=True, verbose_name='Missão')),
                ('visao', models.TextField(blank=True, verbose_name='Visão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Gabinete',
                'verbose_name_plural': 'Gabinetes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Assunto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor para identificação visual', max_length=7, verbose_name='Cor (HEX)')),
                ('icone', models.CharField(blank=True, help_text='Ex: fas fa-heart para saúde', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gabinete', models.ForeignKey(blank=True, help_text='Deixe em branco para assunto global (todos os gabinetes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Assunto/Categoria',
                'verbose_name_plural': 'Assuntos/Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('papel', models.CharField(choices=[('PARLAMENTAR', 'Parlamentar'), ('CHEFE', 'Chefe de Gabinete'), ('ATENDIMENTO', 'Atendimento'), ('JURIDICO', 'Jurídico'), ('COMUNICACAO', 'Comunicação'), ('FINANCEIRO', 'Financeiro'), ('ADMIN', 'Administrador')], default='ATENDIMENTO', max_length=20, verbose_name='Papel')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Modelo')),
                ('tipo', models.CharField(choices=[('OFICIO', 'Ofício'), ('MEMORANDO', 'Memorando'), ('REQUERIMENTO', 'Requerimento'), ('INDICACAO', 'Indicação'), ('MOCAO', 'Moção'), ('PROJETO_LEI', 'Projeto de Lei'), ('EMENDA', 'Emenda')], max_length=20, verbose_name='Tipo')),
                ('conteudo', models.TextField(help_text='Use {{variavel}} para campos dinâmicos', verbose_name='Conteúdo do Template')),
                ('cabecalho', models.TextField(blank=True, verbose_name='Cabeçalho Padrão')),
                ('rodape', models.TextField(blank=True, verbose_name='Rodapé Padrão')),
                ('variaveis_disponiveis', models.TextField(blank=True, help_text='Lista de variáveis que podem ser usadas. Ex: {{destinatario}}, {{data}}, {{numero}}', verbose_name='Variáveis Disponíveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos', to='accounts.assunto', verbose_name='Assunto Padrão')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_documento', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
