# Generated by Django 5.0.6 on 2025-10-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador da justificativa', max_length=200, verbose_name='Nome da Justificativa')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da justificativa', verbose_name='Descrição')),
                ('texto', models.TextField(help_text='Conteúdo da justificativa que será usado nos documentos', verbose_name='Texto da Justificativa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_padrao', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Justificativa Padrão',
                'verbose_name_plural': 'Justificativas Padrão',
                'ordering': ['nome'],
                'unique_together': {('gabinete', 'nome')},
            },
        ),
    ]
