# Generated by Django 5.0.6 on 2025-10-31 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_solicitacaopadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('EXPORT', 'Exportação'), ('APPROVE', 'Aprovação'), ('SIGN', 'Assinatura'), ('SEND', 'Envio'), ('CANCEL', 'Cancelamento')], max_length=20, verbose_name='Ação')),
                ('modulo', models.CharField(help_text='Ex: atendimento, documento, agenda, etc', max_length=50, verbose_name='Módulo')),
                ('objeto_tipo', models.CharField(help_text='Nome do model', max_length=50, verbose_name='Tipo do Objeto')),
                ('objeto_id', models.IntegerField(verbose_name='ID do Objeto')),
                ('objeto_repr', models.CharField(help_text='String representation do objeto', max_length=200, verbose_name='Representação do Objeto')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('dados_anteriores', models.JSONField(blank=True, help_text='Estado do objeto antes da alteração', null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, help_text='Estado do objeto após a alteração', null=True, verbose_name='Dados Novos')),
                ('critico', models.BooleanField(default=False, help_text='Marca ações sensíveis (exclusões, aprovações, assinaturas)', verbose_name='Ação Crítica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='accounts.gabinete', verbose_name='Gabinete')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['gabinete', 'criado_em'], name='accounts_lo_gabinet_331ce7_idx'), models.Index(fields=['usuario', 'criado_em'], name='accounts_lo_usuario_5b63ce_idx'), models.Index(fields=['modulo', 'criado_em'], name='accounts_lo_modulo_9d9c2d_idx'), models.Index(fields=['critico', 'criado_em'], name='accounts_lo_critico_3820c6_idx'), models.Index(fields=['acao', 'criado_em'], name='accounts_lo_acao_4f270e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('ALERTA', 'Alerta'), ('URGENTE', 'Urgente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, help_text='URL interna para onde a notificação leva', max_length=500, verbose_name='Link para Ação')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('enviado_email', models.BooleanField(default=False, verbose_name='E-mail Enviado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['usuario', 'lida', 'criada_em'], name='accounts_no_usuario_4d5334_idx')],
            },
        ),
    ]
