# Generated by Django 5.0.6 on 2025-11-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_logauditoria_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='horario_funcionamento',
            field=models.TextField(blank=True, default='Segunda a Sexta: 08:00 às 12:00 e 14:00 às 18:00\nSábados: Mediante agendamento prévio\nDomingos e Feriados: Fechado', help_text='Informe os horários de atendimento ao público', verbose_name='Horários de Atendimento'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='sla_resposta_solicitacoes',
            field=models.IntegerField(default=72, help_text='Prazo em horas para responder solicitações do cidadão', verbose_name='SLA de Resposta para Solicitações (horas)'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='sla_resposta_visitas',
            field=models.IntegerField(default=48, help_text='Prazo em horas para responder solicitações de visita', verbose_name='SLA de Resposta para Visitas (horas)'),
        ),
    ]
