# Generated by Django 5.0.6 on 2026-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gabinete_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável para o portal público. Ex: vereador-joao-silva', max_length=200, null=True, unique=True, verbose_name='Slug (URL do Portal)'),
        ),
    ]
