# Generated by Django 5.0.6 on 2025-10-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('tipo', models.CharField(choices=[('ELEITOR', 'Eleitor'), ('LIDERANCA', 'Liderança'), ('PARCEIRO', 'Parceiro'), ('ORGAO', 'Órgão Público')], default='ELEITOR', max_length=20, verbose_name='Tipo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('zona_eleitoral', models.CharField(blank=True, max_length=50, verbose_name='Zona Eleitoral')),
                ('consentiu_contato', models.BooleanField(default=False, verbose_name='Consentiu para contato')),
                ('consentido_em', models.DateTimeField(blank=True, null=True, verbose_name='Consentido em')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem do contato')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (separadas por vírgula)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
                'unique_together': {('gabinete', 'cpf')},
            },
        ),
    ]
