# Generated by Django 5.0.6 on 2025-10-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agenda', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True, verbose_name='Protocolo')),
                ('tipo_solicitante', models.CharField(choices=[('CIDADAO', 'Cidadão'), ('ENTIDADE', 'Entidade/Associação'), ('EMPRESA', 'Empresa'), ('ORGAO_PUBLICO', 'Órgão Público'), ('VEREADOR', 'Vereador'), ('DEPUTADO', 'Deputado'), ('PREFEITO', 'Prefeito'), ('SECRETARIA', 'Secretaria'), ('ONG', 'ONG'), ('SINDICATO', 'Sindicato'), ('OUTRO', 'Outro')], default='CIDADAO', max_length=20, verbose_name='Tipo de Solicitante')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto/Título')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Crítica')], default=2, verbose_name='Prioridade')),
                ('origem', models.CharField(choices=[('PRESENCIAL', 'Atendimento Presencial'), ('TELEFONE', 'Telefone'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('PORTAL', 'Portal do Cidadão'), ('REDES_SOCIAIS', 'Redes Sociais'), ('OFICIO', 'Ofício Recebido'), ('INDICACAO', 'Indicação'), ('AUDIENCIA', 'Audiência Pública'), ('REUNIAO', 'Reunião'), ('OUTRO', 'Outro')], default='PRESENCIAL', max_length=20, verbose_name='Canal de Origem')),
                ('origem_detalhes', models.CharField(blank=True, help_text='Ex: nome da rede social, número do ofício, etc.', max_length=200, verbose_name='Detalhes da Origem')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo para Resolução')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('endereco_referencia', models.TextField(blank=True, verbose_name='Endereço/Referência')),
                ('satisfacao', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Avaliação de Satisfação')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback do Cidadão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('solucao', models.TextField(blank=True, verbose_name='Solução/Encaminhamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='accounts.assunto', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento_origem', models.ForeignKey(blank=True, help_text='Se este atendimento foi gerado a partir de uma reunião/evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_gerados', to='agenda.evento', verbose_name='Evento de Origem')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='accounts.gabinete', verbose_name='Gabinete')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='crm.pessoa', verbose_name='Solicitante')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('tipo', models.CharField(choices=[('PROTOCOLO', 'Protocolo'), ('OFICIO', 'Ofício'), ('MEMORANDO', 'Memorando'), ('REQUERIMENTO', 'Requerimento'), ('INDICACAO', 'Indicação')], max_length=20, verbose_name='Tipo')),
                ('numero', models.IntegerField(default=0, verbose_name='Último Número')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencias', to='accounts.gabinete', verbose_name='Gabinete')),
            ],
            options={
                'verbose_name': 'Sequência',
                'verbose_name_plural': 'Sequências',
                'ordering': ['gabinete', 'ano', 'tipo'],
                'unique_together': {('gabinete', 'ano', 'tipo')},
            },
        ),
    ]
